title: Koen Raijer
author:
  name: Koen Raijer
  email: koenraijer@protonmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  ðŸ‘‹ I'm a 22-year old fifth year medicine student from the Netherlands. I write about health tech, mental health and psychedelics research, data science, programming, and ethics. I like working out, playing music, reading books and getting sucked into internet deep dives.

show_excerpts: true # set to true to show excerpts on the homepage
include: ['_tags']
relative_permalinks: false

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d-%m-%Y"

  # generate social links in footer
  social_links:
    twitter: koenraijer
    linkedin: https://www.linkedin.com/in/koen-raijer-3495a7127/
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  skin: myskin

posts:
  permalink: /:categories/:year/:month/:day/:title/